name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code

      - name: Build application
        run: sudo apt-get install libsfml-dev && make
      
      - name: Test application
        run: make test